In [1]:
import numpy

In [2]:
a=numpy.array([1,2,3])

In [3]:
print a

[1 2 3]


In [10]:
mat=numpy.array([[1,0,5],[0,5,10]])

In [11]:
print mat

[[ 1  0  5]
 [ 0  5 10]]


In [14]:
print mat.T

[[ 1  0]
 [ 0  5]
 [ 5 10]]


In [15]:
cmat=numpy.array(mat,dtype=numpy.complex)

In [16]:
print cmat

[[  1.+0.j   0.+0.j   5.+0.j]
 [  0.+0.j   5.+0.j  10.+0.j]]


In [17]:
print numpy.arange(10)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
print numpy.zeros((5,1))

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [19]:
print numpy.ones((5,2))

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [23]:
print numpy.linspace(0,1,101)

[ 0.    0.01  0.02  0.03  0.04  0.05  0.06  0.07  0.08  0.09  0.1   0.11
  0.12  0.13  0.14  0.15  0.16  0.17  0.18  0.19  0.2   0.21  0.22  0.23
  0.24  0.25  0.26  0.27  0.28  0.29  0.3   0.31  0.32  0.33  0.34  0.35
  0.36  0.37  0.38  0.39  0.4   0.41  0.42  0.43  0.44  0.45  0.46  0.47
  0.48  0.49  0.5   0.51  0.52  0.53  0.54  0.55  0.56  0.57  0.58  0.59
  0.6   0.61  0.62  0.63  0.64  0.65  0.66  0.67  0.68  0.69  0.7   0.71
  0.72  0.73  0.74  0.75  0.76  0.77  0.78  0.79  0.8   0.81  0.82  0.83
  0.84  0.85  0.86  0.87  0.88  0.89  0.9   0.91  0.92  0.93  0.94  0.95
  0.96  0.97  0.98  0.99  1.  ]


In [22]:
print numpy.identity(2)

[[ 1.  0.]
 [ 0.  1.]]


In [24]:
x=numpy.array([0,1,2,3,4])
y=numpy.array([-1,0,1])

In [25]:
grid=numpy.meshgrid(x,y)

In [26]:
print grid

[array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]]), array([[-1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1]])]


In [27]:
print mat

[[ 1  0  5]
 [ 0  5 10]]


In [29]:
mat=numpy.array([[1,0,5], [0,5,10],[0,6,2]])

In [30]:
5*mat

array([[ 5,  0, 25],
       [ 0, 25, 50],
       [ 0, 30, 10]])

In [31]:
a=numpy.arange(1,6)

In [32]:
b=numpy.arange(6,11)

In [33]:
a*b

array([ 6, 14, 24, 36, 50])

In [34]:
a**2

array([ 1,  4,  9, 16, 25])

In [35]:
a>2

array([False, False,  True,  True,  True], dtype=bool)

In [36]:
I=numpy.identity(3)

In [42]:
print mat.dot(I)

[[  1.   0.   5.]
 [  0.   5.  10.]
 [  0.   6.   2.]]


In [43]:
a.dot(b)

130

In [45]:
print numpy.linalg.det(mat)

-50.0


In [47]:
mati=numpy.linalg.inv(mat)
print mati

[[ 1.   -0.6   0.5 ]
 [ 0.   -0.04  0.2 ]
 [ 0.    0.12 -0.1 ]]


In [48]:
print mati.dot(mat)

[[  1.00000000e+00  -4.44089210e-16  -1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00   5.55111512e-17]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]


In [49]:
numpy.trace(I)

3.0

In [60]:
I.trace()

3.0

In [52]:
print numpy.linalg.eigvals(mat)

[  1.          11.38986692  -4.38986692]


In [55]:
print numpy.linalg.eigvals(mat)

[  1.          11.38986692  -4.38986692]


In [56]:
print a

[1 2 3 4 5]


In [57]:
print numpy.cos(a)

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [59]:
print a.sum()

15


In [61]:
print mat.max()

10


In [62]:
print a.mean()

3.0


In [63]:
print numpy.random.standard_normal()

-0.075682608256


In [64]:
print numpy.random.standard_normal()

-0.293614207544


In [65]:
print numpy.random.standard_normal()

-0.189617568234


In [66]:
print b

[ 6  7  8  9 10]


In [67]:
print a

[1 2 3 4 5]


Si hacemos b=a se le da un apuntador b en la dirección de a.

Se debe hacer b=a.copy()

In [69]:
b=a
b[0]=-1

In [70]:
print a,b

[-1  2  3  4  5] [-1  2  3  4  5]
